# Install and/or upgrade NGINX Plus in the Specificied environment

variables:
  ADO_ENV: $(azureDevOpsEnvironment)
  ADO_TAG: $(azureDevOpsTag)
  NAP: true
  NGINX_REPO_KEY: $(nginxRepoKey)
  NGINX_REPO_CRT: $(nginxRepoCrt)
  APT_SYSTEM: debian                    # debian or ubuntu

trigger:
- none

jobs: 
- deployment: NGNIXDeploy
  displayName: NGINX Plus Deployment
  environment:
    name: $(ADO_ENV)
    resourceType: VirtualMachine
  strategy:
      rolling:
        maxParallel: 2
        deploy:

          steps:
          - task: Bash@3
            displayName: Setup NGINX Plus repository certs
            inputs:
              targetType: 'inline'
              script: |
                if [ ! -d '/etc/ssl/nginx' ]
                then
                  sudo mkdir -p /etc/ssl/nginx
                fi
                echo $(NGINX_REPO_KEY) | base64 -d | sudo tee /etc/ssl/nginx/nginx-repo.key
                echo $(NGINX_REPO_CRT) | base64 -d | sudo tee /etc/ssl/nginx/nginx-repo.crt
          - task: Bash@3
            displayName: Setup Apt
            inputs:
              targetType: 'inline'
              script: |
                export DEBIAN_FRONTEND=noninteractive
                sudo -E apt-get install -y apt-transport-https lsb-release ca-certificates
                sudo wget https://cs.nginx.com/static/keys/nginx_signing.key && sudo apt-key add nginx_signing.key
                printf "deb https://plus-pkgs.nginx.com/$(APT_SYSTEM) `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nginx-plus.list
                [ -f /etc/apt/apt.conf.d/90nginx ] || sudo wget -P /etc/apt/apt.conf.d https://cs.nginx.com/static/files/90nginx
                if [ "$(NAP)" == "true" ]
                then
                  sudo wget https://cs.nginx.com/static/keys/app-protect.key && sudo apt-key add app-protect.key
                  printf "deb https://app-protect-sigs.nginx.com/$(APT_SYSTEM) `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/app-protect-sigs.list
                  [ -f /etc/apt/apt.conf.d/90app-protect-sigs ] || sudo wget -P /etc/apt/apt.conf.d https://cs.nginx.com/static/files/90app-protect-sigs
                fi
          - task: Bash@3
            displayName: Install NGINX Plus
            inputs:
              targetType: 'inline'
              script: |
                export DEBIAN_FRONTEND=noninteractive
                sudo -E apt-get update
                dpkg -l | grep nginx-plus || sudo -E apt-get -y install nginx-plus
                dpkg -l | grep app-protect || [ "$(NAP)" == "true" ] && sudo -E apt-get install -y app-protect app-protect-attack-signatures
        on:
          failure:
            steps:
            - script: echo Restore from backup! This is on failure
          success:
            steps:
            - script: echo Notify! This is on success
