# Install and/or upgrade NGINX Plus in the Specificied environment

variables:
  ADO_ENV: $(azureDevOpsEnvironment)
  ADO_TAG: $(azureDevOpsTag)
  NAP: false
  NIGNX_REPO_KEY: $(nginxRepoKey)
  NGINX_REPO_CRT: $(nginxRepoCrt)

trigger:
- none

jobs: 
- deployment: NGNIXDeploy
  displayName: NGINX Plus Deployment
  environment:
    name: $(ADO_ENV)
    resourceType: VirtualMachine
  strategy:
      rolling:
        maxParallel: 2
        preDeploy:
          steps:
          - download: current
            artifact: drop
          - script: echo initialize, cleanup, backup, install certs
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo $(NAP)
        routeTraffic:
          steps:
          - script: echo routing traffic
        postRouteTraffic:
          steps:
          - script: echo health check post-route traffic
        on:
          failure:
            steps:
            - script: echo Restore from backup! This is on failure
          success:
            steps:
            - script: echo Notify! This is on success
